---
apiVersion: v1
kind: Namespace
metadata:
  name: omnitools
  labels:
    name: omnitools
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnitools-deployment
  namespace: omnitools
  labels:
    app: omnitools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omnitools
  template:
    metadata:
      labels:
        app: omnitools
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: omnitools
        image: iib0011/omnitools:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 101
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: omnitools-service
  namespace: omnitools
spec:
  type: ClusterIP
  selector:
    app: omnitools
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
